In [1]:
import pandas as pd
from io import StringIO

In [2]:
## Manual extract HTML Table for Apr 2024
## 1. Browse https://www.google.com/search?q=prayer+times+in+kuala+lumpur
## 2. Tabs "Today" and "30 days", click on "30 days"
## 3. Click "More days" to expand the table, showing all 30 rows
## 4. Inspect element, click tab Console, then type in "document.getElementsByClassName("bvYrdf")[1].innerHTML;" and hit Enter
## 5. Copy the texts appeared below it into the variable GoogleSearchWidgetApr2024 below
##
## MAKE SURE TO RUN THIS ON:
## 2nd of each month to get the first 30 days of the month
## 3rd of the month to get the row data for 31st

In [3]:
filePath = 'htmldata\googlesearch_2024_04.txt'

with open(filePath, 'r') as file:
    lines = file.readlines()
    fileContent = ''.join(lines).replace(r'\g+', '')

GoogleSearchWidgetApr2024 = fileContent

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\azams\AppData\Local\Temp\ipykernel_14220\2916470486.py:1: SyntaxWarning: invalid escape sequence '\g'
  filePath = 'htmldata\googlesearch_2024_04.txt'

In [4]:
GoogleSearchDFApr2024 = pd.read_html(StringIO(str(GoogleSearchWidgetApr2024)))[0]
GoogleSearchDFApr2024.iloc[0,0] = "2024"
GoogleSearchDFApr2024.columns = GoogleSearchDFApr2024.iloc[0]
GoogleSearchDFApr2024 = GoogleSearchDFApr2024[1:]

In [5]:
GoogleSearchDFApr2024

0     2024   Fajr Sunrise  Dhuhr    Asr Maghrib   Isha
1    1 Apr  06:07   07:13  13:18  16:22   19:22  20:31
2    2 Apr  06:06   07:12  13:18  16:22   19:22  20:31
3    3 Apr  06:06   07:12  13:18  16:23   19:22  20:31
4    4 Apr  06:05   07:12  13:17  16:23   19:22  20:31
5    5 Apr  06:05   07:11  13:17  16:23   19:22  20:31
6    6 Apr  06:04   07:11  13:17  16:24   19:21  20:31
7    7 Apr  06:04   07:10  13:16  16:24   19:21  20:31
8    8 Apr  06:04   07:10  13:16  16:25   19:21  20:30
9    9 Apr  06:03   07:10  13:16  16:25   19:21  20:30
10  10 Apr  06:03   07:09  13:16  16:25   19:21  20:30
11  11 Apr  06:02   07:09  13:15  16:26   19:20  20:30
12  12 Apr  06:02   07:09  13:15  16:26   19:20  20:30
13  13 Apr  06:01   07:08  13:15  16:26   19:20  20:30
14  14 Apr  06:01   07:08  13:15  16:26   19:20  20:30
15  15 Apr  06:01   07:08  13:14  16:27   19:20  20:30
16  16 Apr  06:00   07:07  13:14  16:27   19:20  20:30
17  17 Apr  06:00   07:07  13:14  16:27   19:19  20:30
18  18 Apr  05:59   07:07  13:14  16:28   19:19  20:30
19  19 Apr  05:59   07:06  13:13  16:28   19:19  20:30
20  20 Apr  05:59   07:06  13:13  16:28   19:19  20:30
21  21 Apr  05:58   07:06  13:13  16:28   19:19  20:30
22  22 Apr  05:58   07:06  13:13  16:29   19:19  20:30
23  23 Apr  05:57   07:05  13:13  16:29   19:19  20:29
24  24 Apr  05:57   07:05  13:12  16:29   19:19  20:30
25  25 Apr  05:57   07:05  13:12  16:29   19:19  20:30
26  26 Apr  05:56   07:05  13:12  16:30   19:18  20:30
27  27 Apr  05:56   07:04  13:12  16:30   19:18  20:30
28  28 Apr  05:56   07:04  13:12  16:30   19:18  20:30
29  29 Apr  05:55   07:04  13:12  16:30   19:18  20:30
30  30 Apr  05:55   07:04  13:12  16:31   19:18  20:30

In [6]:
dfApr2024 = GoogleSearchDFApr2024[["2024","Fajr","Dhuhr","Asr","Maghrib","Isha"]]
dfApr2024.loc[:,"2024"] = pd.to_datetime(dfApr2024["2024"].astype(str) + " 2024", format="%d %b %Y").dt.date
dfApr2024.loc[:,"Fajr"] = pd.to_datetime(dfApr2024["Fajr"], format="%H:%M").dt.time
dfApr2024.loc[:,"Dhuhr"] = pd.to_datetime(dfApr2024["Dhuhr"], format="%H:%M").dt.time
dfApr2024.loc[:,"Asr"] = pd.to_datetime(dfApr2024["Asr"], format="%H:%M").dt.time
dfApr2024.loc[:,"Maghrib"] = pd.to_datetime(dfApr2024["Maghrib"], format="%H:%M").dt.time
dfApr2024.loc[:,"Isha"] = pd.to_datetime(dfApr2024["Isha"], format="%H:%M").dt.time

In [7]:
dfApr2024

0         2024      Fajr     Dhuhr       Asr   Maghrib      Isha
1   2024-04-01  06:07:00  13:18:00  16:22:00  19:22:00  20:31:00
2   2024-04-02  06:06:00  13:18:00  16:22:00  19:22:00  20:31:00
3   2024-04-03  06:06:00  13:18:00  16:23:00  19:22:00  20:31:00
4   2024-04-04  06:05:00  13:17:00  16:23:00  19:22:00  20:31:00
5   2024-04-05  06:05:00  13:17:00  16:23:00  19:22:00  20:31:00
6   2024-04-06  06:04:00  13:17:00  16:24:00  19:21:00  20:31:00
7   2024-04-07  06:04:00  13:16:00  16:24:00  19:21:00  20:31:00
8   2024-04-08  06:04:00  13:16:00  16:25:00  19:21:00  20:30:00
9   2024-04-09  06:03:00  13:16:00  16:25:00  19:21:00  20:30:00
10  2024-04-10  06:03:00  13:16:00  16:25:00  19:21:00  20:30:00
11  2024-04-11  06:02:00  13:15:00  16:26:00  19:20:00  20:30:00
12  2024-04-12  06:02:00  13:15:00  16:26:00  19:20:00  20:30:00
13  2024-04-13  06:01:00  13:15:00  16:26:00  19:20:00  20:30:00
14  2024-04-14  06:01:00  13:15:00  16:26:00  19:20:00  20:30:00
15  2024-04-15  06:01:00  13:14:00  16:27:00  19:20:00  20:30:00
16  2024-04-16  06:00:00  13:14:00  16:27:00  19:20:00  20:30:00
17  2024-04-17  06:00:00  13:14:00  16:27:00  19:19:00  20:30:00
18  2024-04-18  05:59:00  13:14:00  16:28:00  19:19:00  20:30:00
19  2024-04-19  05:59:00  13:13:00  16:28:00  19:19:00  20:30:00
20  2024-04-20  05:59:00  13:13:00  16:28:00  19:19:00  20:30:00
21  2024-04-21  05:58:00  13:13:00  16:28:00  19:19:00  20:30:00
22  2024-04-22  05:58:00  13:13:00  16:29:00  19:19:00  20:30:00
23  2024-04-23  05:57:00  13:13:00  16:29:00  19:19:00  20:29:00
24  2024-04-24  05:57:00  13:12:00  16:29:00  19:19:00  20:30:00
25  2024-04-25  05:57:00  13:12:00  16:29:00  19:19:00  20:30:00
26  2024-04-26  05:56:00  13:12:00  16:30:00  19:18:00  20:30:00
27  2024-04-27  05:56:00  13:12:00  16:30:00  19:18:00  20:30:00
28  2024-04-28  05:56:00  13:12:00  16:30:00  19:18:00  20:30:00
29  2024-04-29  05:55:00  13:12:00  16:30:00  19:18:00  20:30:00
30  2024-04-30  05:55:00  13:12:00  16:31:00  19:18:00  20:30:00

In [8]:
## use same technique in e-Solat JAKIM extraction to save df to db
import pyodbc

connStr = "DRIVER={ODBC Driver 17 for SQL Server};SERVER=INBOOK_X1;DATABASE=PrayerTimesDW;UID=sa;PWD=abcdE!2345;"
conn = pyodbc.connect(connStr)
# cursor = conn.cursor()

In [9]:
# for idx, row in dfJan2024.iterrows():
    # cursor.execute("INSERT INTO [dbo].[t_time_prayer_source_2] ([time_date],[time_fajr],[time_zuhr],[time_asr],[time_maghrib],[time_isha]) VALUES (?,?,?,?,?,?)", row["January"], row["Fajr"], row["Dhuhr"], row["Asr"], row["Maghrib"], row["Isha"])

# conn.commit()
# cursor.close()
conn.close()